# HR-INSIGHTS

## Data Exploration

In [1]:
# Importation des bibliothèques

from pathlib import Path

import sys



# -----------------------------------------------------

# Ajouter la racine du projet (HR-INSIGHTS) au PYTHONPATH

# afin de pouvoir importer les modules du dossier src.

# -----------------------------------------------------

PROJECT_ROOT = Path.cwd().parent



if str(PROJECT_ROOT) not in sys.path:

    sys.path.append(str(PROJECT_ROOT))



# -----------------------------------------------------

# Import de la fonction de lecture Excel

# -----------------------------------------------------

from src.data_loader import load_excel

In [2]:
# Définition du chemin du fichier Excel

# -----------------------------------------------------

DATA_PATH = PROJECT_ROOT / "data" / "raw" / "situation_administrative.xlsx"



# -----------------------------------------------------

# Chargement des données

# -----------------------------------------------------

df = load_excel(DATA_PATH)

## Aperçu des données

In [3]:
# Affichage des 5 premières lignes
df.head()

,N,P.P.R.,Matricule,Noms et Prénoms,Date de Naissances,Date de recrutement,Date de mise à la retraite,Sexe,C.I.N.,Date de titularisation,...,Echellon,Indice,Date d'échelon,n° d'arrêté,Date d'arrêté,Date de grade,Observations,Unnamed: 21,@,Statut
0,1,9077047.0,10316.0,ABARAY Lahcen,1970-12-31,2001-03-30,2033-12-31,H,JB96972,2004-10-01 00:00:00,...,3,779,2022-11-01 00:00:00,19853,2023-11-21,2017-01-01,NaN,Oubella,NaN,NaN
1,2,9077033.0,10299.0,ADILA Miloud,1963-08-02,1995-11-13,2026-08-02,H,J209988,1996-11-13 00:00:00,...,5,840,2024-01-01 00:00:00,19893,2025-11-26,2015-01-01,NaN,Oubella,NaN,NaN
2,3,9077019.0,10283.0,ADMOR Mohamed,1966-12-31,1992-10-12,2029-12-31,H,JB2440,1993-10-12 00:00:00,...,4,812,2023-01-01 00:00:00,22314,2024-12-26,2017-01-01,NaN,Oubella,NaN,NaN
3,4,9077016.0,10280.0,AIT JEDDI Mohamed,1966-11-20,1994-02-01,2029-11-20,H,JB21553,1995-02-01 00:00:00,...,4,812,2024-01-01 00:00:00,19881,2025-11-26,2018-01-01,NaN,Oubella,NaN,NaN
4,5,9077009.0,10273.0,AL OUATIQ Latifa,1967-03-15,1995-08-01,2030-03-15,F,JC11827,1997-07-01 00:00:00,...,4,812,2024-01-01 00:00:00,19892,2025-11-26,2018-01-01,NaN,Oubella,NaN,NaN

## Dimensions du DataFrame

In [4]:
df.shape

(1093, 24)

## Informations générales

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   N                               1093 non-null   int64
 1   P.P.R.                          1092 non-null   float64
 2   Matricule                       987 non-null    float64
 3   Noms et Prénoms                 1093 non-null   str
 4   Date   de  Naissances           1093 non-null   datetime64[us]
 5   Date de recrutement             1093 non-null   datetime64[us]
 6   Date de mise à la retraite      1092 non-null   datetime64[us]
 7   Sexe                            1093 non-null   str
 8   C.I.N.                          1093 non-null   str
 9   Date de titularisation          1044 non-null   object
 10  N° Affiliation à la C.M.R       985 non-null    object
 11  Date d'affiliation à la C.M.R.  995 non-null    object
 12  Grade                           1093 non-null   str
 13  Echelle                         1093 non-null   object
 14  Echellon                        1093 non-null   object
 15  Indice                          1093 non-null   int64
 16  Date d'échelon                  1093 non-null   object
 17  n° d'arrêté                     1084 non-null   object
 18  Date d'arrêté                   1086 non-null   datetime64[us]
 19  Date de grade                   1093 non-null   datetime64[us]
 20  Observations                    1 non-null      str
 21  Unnamed: 21                     1054 non-null   str
 22  @                               1 non-null      str
 23  Statut                          39 non-null     str
dtypes: datetime64[us](5), float64(2), int64(2), object(7), str(8)
memory usage: 264.2+ KB

## Colonnes

In [6]:
df.columns.tolist()

['N',
 'P.P.R.',
 'Matricule',
 'Noms et Prénoms',
 'Date   de  Naissances',
 'Date de recrutement ',
 'Date de mise à la retraite ',
 'Sexe',
 'C.I.N.',
 'Date de titularisation ',
 'N° Affiliation à la C.M.R',
 "Date d'affiliation à la C.M.R.",
 'Grade',
 'Echelle',
 'Echellon',
 'Indice ',
 "Date d'échelon ",
 "n° d'arrêté ",
 "Date d'arrêté ",
 'Date de grade ',
 'Observations',
 'Unnamed: 21',
 '@',
 'Statut']

## Valeurs manquantes

In [7]:
df.isna().sum()

N                                    0
P.P.R.                               1
Matricule                          106
Noms et Prénoms                      0
Date   de  Naissances                0
Date de recrutement                  0
Date de mise à la retraite           1
Sexe                                 0
C.I.N.                               0
Date de titularisation              49
N° Affiliation à la C.M.R          108
Date d'affiliation à la C.M.R.      98
Grade                                0
Echelle                              0
Echellon                             0
Indice                               0
Date d'échelon                       0
n° d'arrêté                          9
Date d'arrêté                        7
Date de grade                        0
Observations                      1092
Unnamed: 21                         39
@                                 1092
Statut                            1054
dtype: int64

## Doublons

In [8]:
df.duplicated().sum()

np.int64(0)

## Statistiques descriptives

In [9]:
df.describe(include="all")

,N,P.P.R.,Matricule,Noms et Prénoms,Date de Naissances,Date de recrutement,Date de mise à la retraite,Sexe,C.I.N.,Date de titularisation,...,Echellon,Indice,Date d'échelon,n° d'arrêté,Date d'arrêté,Date de grade,Observations,Unnamed: 21,@,Statut
count,1093.000000,1.092000e+03,987.000000,1093,1093,1093,1092,1093,1093,1044,...,1093.0,1093.000000,1093,1084.0,1086,1093,1,1054,1,39
unique,NaN,NaN,NaN,1092,NaN,NaN,NaN,2,1093,206,...,13.0,NaN,287,1013.0,NaN,NaN,1,11,1,1
top,NaN,NaN,NaN,AIT AHMED Mohamed,NaN,NaN,NaN,H,JB96972,2013-01-01 00:00:00,...,9.0,NaN,2022-01-02 00:00:00,6349.0,NaN,NaN,Détachée de la commune de Meknes 01/02/2025,Abdellah,izaabel,Stagiaire
freq,NaN,NaN,NaN,2,NaN,NaN,NaN,871,1,87,...,200.0,NaN,71,3.0,NaN,NaN,1,225,1,39
mean,547.000000,8.217136e+06,14527.550152,NaN,1974-04-02 18:08:14.053064,2001-05-26 19:03:34.089661,2037-04-08 06:07:54.725274,NaN,NaN,NaN,...,NaN,362.881061,NaN,NaN,2023-09-14 00:35:48.066298,2021-07-23 13:27:36.724611,NaN,NaN,NaN,NaN
min,1.000000,1.767951e+06,10008.000000,NaN,1956-12-31 00:00:00,1982-04-01 00:00:00,2026-08-02 00:00:00,NaN,NaN,NaN,...,NaN,4.000000,NaN,NaN,2014-08-12 00:00:00,2005-12-31 00:00:00,NaN,NaN,NaN,NaN
25%,274.000000,9.077232e+06,11675.500000,NaN,1967-03-01 00:00:00,1994-02-04 00:00:00,2030-03-03 06:00:00,NaN,NaN,NaN,...,NaN,259.000000,NaN,NaN,2023-03-03 00:00:00,2019-12-31 00:00:00,NaN,NaN,NaN,NaN
50%,547.000000,9.078086e+06,15380.000000,NaN,1971-08-05 00:00:00,1998-07-01 00:00:00,2034-08-07 12:00:00,NaN,NaN,NaN,...,NaN,311.000000,NaN,NaN,2024-02-01 00:00:00,2023-01-01 00:00:00,NaN,NaN,NaN,NaN
75%,820.000000,9.078540e+06,16684.500000,NaN,1978-01-02 00:00:00,2007-12-01 00:00:00,2041-01-03 00:00:00,NaN,NaN,NaN,...,NaN,402.000000,NaN,NaN,2025-03-10 00:00:00,2024-01-02 00:00:00,NaN,NaN,NaN,NaN
max,1093.000000,9.078958e+06,18073.000000,NaN,2005-06-15 00:00:00,2026-05-04 00:00:00,2068-06-15 00:00:00,NaN,NaN,NaN,...,NaN,960.000000,NaN,NaN,2026-06-12 00:00:00,2026-06-22 00:00:00,NaN,NaN,NaN,NaN
std,315.666227,2.275839e+06,2505.306364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,155.040608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Suppression des colonnes inutiles

In [10]:
from src.data_cleaning import drop_unused_columns

df = drop_unused_columns(df)

df.columns.tolist()

['N',
 'P.P.R.',
 'Matricule',
 'Noms et Prénoms',
 'Date   de  Naissances',
 'Date de recrutement ',
 'Date de mise à la retraite ',
 'Sexe',
 'C.I.N.',
 'Date de titularisation ',
 'N° Affiliation à la C.M.R',
 "Date d'affiliation à la C.M.R.",
 'Grade',
 'Echelle',
 'Echellon',
 'Indice ',
 "Date d'échelon ",
 "n° d'arrêté ",
 "Date d'arrêté ",
 'Date de grade ']

## Conversion des colonnes de dates

In [11]:
from src.data_cleaning import convert_date_columns

df = convert_date_columns(df)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   N                               1093 non-null   int64
 1   P.P.R.                          1092 non-null   float64
 2   Matricule                       987 non-null    float64
 3   Noms et Prénoms                 1093 non-null   str
 4   Date   de  Naissances           1093 non-null   datetime64[us]
 5   Date de recrutement             1093 non-null   datetime64[us]
 6   Date de mise à la retraite      1092 non-null   datetime64[us]
 7   Sexe                            1093 non-null   str
 8   C.I.N.                          1093 non-null   str
 9   Date de titularisation          1043 non-null   datetime64[us]
 10  N° Affiliation à la C.M.R       985 non-null    object
 11  Date d'affiliation à la C.M.R.  994 non-null    datetime64[us]
 12  Grade                           1093 non-null   str
 13  Echelle                         1093 non-null   object
 14  Echellon                        1093 non-null   object
 15  Indice                          1093 non-null   int64
 16  Date d'échelon                  1093 non-null   datetime64[us]
 17  n° d'arrêté                     1084 non-null   object
 18  Date d'arrêté                   1086 non-null   datetime64[us]
 19  Date de grade                   1093 non-null   datetime64[us]
dtypes: datetime64[us](8), float64(2), int64(2), object(4), str(4)
memory usage: 223.3+ KB