# HR-INSIGHTS

## Sprint 3 - Feature Engineering

### Objectif

Dans ce notebook, nous allons :

- Charger les données RH.
- Nettoyer les données.
- Créer de nouvelles variables (Feature Engineering).
- Préparer les données pour les analyses et le futur dashboard.

In [1]:
# =====================================================
# Configuration du projet
# =====================================================

# Importation des bibliothèques
from pathlib import Path
import sys

# -----------------------------------------------------
# Ajouter la racine du projet au PYTHONPATH
# -----------------------------------------------------
PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

## 1. Importation des modules

Import des fonctions développées dans le dossier `src`.

In [2]:
# -----------------------------------------------------
# Import des fonctions
# -----------------------------------------------------
from src.data_loader import load_excel
from src.data_cleaning import (
    clean_column_names,
    drop_unused_columns,
    convert_date_columns,
)
from src.feature_engineering import apply_feature_engineering

## 2. Chargement des données

Lecture du fichier Excel contenant la situation administrative.

In [3]:

DATA_PATH = PROJECT_ROOT / "data" / "raw" / "situation_administrative.xlsx"

df = load_excel(DATA_PATH)

## 3. Nettoyage des données

Application des fonctions de nettoyage développées dans `data_cleaning.py`.

In [4]:
df = clean_column_names(df)

df = drop_unused_columns(df)

df = convert_date_columns(df)

## 4. Vérification des données

Contrôle rapide de la structure du DataFrame après le nettoyage.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      1093 non-null   int64
 1   ppr                     1092 non-null   float64
 2   matricule               987 non-null    float64
 3   nom_prenom              1093 non-null   str
 4   date_naissance          1093 non-null   datetime64[us]
 5   date_recrutement        1093 non-null   datetime64[us]
 6   date_retraite           1092 non-null   datetime64[us]
 7   sexe                    1093 non-null   str
 8   cin                     1093 non-null   str
 9   date_titularisation     1044 non-null   object
 10  numero_affiliation_cmr  985 non-null    object
 11  date_affiliation_cmr    995 non-null    object
 12  grade                   1093 non-null   str
 13  echelle                 1093 non-null   object
 14  echelon                 1093 non-null   object
 15  indice                  1093 non-null   int64
 16  date_echelon            1093 non-null   object
 17  numero_arrete           1084 non-null   object
 18  date_arrete             1086 non-null   datetime64[us]
 19  date_grade              1093 non-null   datetime64[us]
 20  observations            1 non-null      str
 21  unnamed_21              1054 non-null   str
 22  at                      1 non-null      str
 23  statut                  39 non-null     str
dtypes: datetime64[us](5), float64(2), int64(2), object(7), str(8)
memory usage: 264.2+ KB

In [6]:
df.head()

,id,ppr,matricule,nom_prenom,date_naissance,date_recrutement,date_retraite,sexe,cin,date_titularisation,...,echelon,indice,date_echelon,numero_arrete,date_arrete,date_grade,observations,unnamed_21,at,statut
0,1,9077047.0,10316.0,ABARAY Lahcen,1970-12-31,2001-03-30,2033-12-31,H,JB96972,2004-10-01 00:00:00,...,3,779,2022-11-01 00:00:00,19853,2023-11-21,2017-01-01,NaN,Oubella,NaN,NaN
1,2,9077033.0,10299.0,ADILA Miloud,1963-08-02,1995-11-13,2026-08-02,H,J209988,1996-11-13 00:00:00,...,5,840,2024-01-01 00:00:00,19893,2025-11-26,2015-01-01,NaN,Oubella,NaN,NaN
2,3,9077019.0,10283.0,ADMOR Mohamed,1966-12-31,1992-10-12,2029-12-31,H,JB2440,1993-10-12 00:00:00,...,4,812,2023-01-01 00:00:00,22314,2024-12-26,2017-01-01,NaN,Oubella,NaN,NaN
3,4,9077016.0,10280.0,AIT JEDDI Mohamed,1966-11-20,1994-02-01,2029-11-20,H,JB21553,1995-02-01 00:00:00,...,4,812,2024-01-01 00:00:00,19881,2025-11-26,2018-01-01,NaN,Oubella,NaN,NaN
4,5,9077009.0,10273.0,AL OUATIQ Latifa,1967-03-15,1995-08-01,2030-03-15,F,JC11827,1997-07-01 00:00:00,...,4,812,2024-01-01 00:00:00,19892,2025-11-26,2018-01-01,NaN,Oubella,NaN,NaN

In [7]:
df = apply_feature_engineering(df)

## 5. Feature Engineering

Création de nouvelles variables qui seront utilisées dans les indicateurs RH.

## 6. Vérification de la nouvelle variable

Affichage des premières lignes pour vérifier le calcul de l'âge.

In [8]:
df[
    [
        "nom_prenom",
        "date_naissance",
        "age",
    ]
].head(10)

           nom_prenom date_naissance  age
0       ABARAY Lahcen     1970-12-31   55
1       ADILA  Miloud     1963-08-02   63
2       ADMOR Mohamed     1966-12-31   59
3   AIT JEDDI Mohamed     1966-11-20   59
4   AL OUATIQ  Latifa     1967-03-15   59
5     AMAJOUD  Lahcen     1968-12-31   57
6   AMSAGGUINE Rachid     1974-01-03   52
7  BENMOHAMED  Lahcen     1967-12-30   58
8    DIBI  El Mostafa     1963-10-18   62
9  EL FELLAKI Khadija     1966-12-06   59

## 7. Statistiques descriptives

Analyse rapide de la nouvelle variable.

In [9]:
df["age"].describe()

count    1093.000000
mean       51.836231
std         9.573682
min        21.000000
25%        48.000000
50%        55.000000
75%        59.000000
max        69.000000
Name: age, dtype: float64

In [10]:
df["age"].value_counts().sort_index()

age
21     4
22     2
23     3
24     5
25    13
26     7
27     7
28     6
29     7
30     9
31     6
32     4
33     6
34     3
35    15
36     8
37    11
38     6
39    11
40    16
41    13
42    12
43    12
44    11
45    20
46    23
47    15
48    29
49    27
50    33
51    52
52    47
53    51
54    51
55    44
56    65
57    56
58    74
59    81
60    69
61    76
62    80
63     2
69     1
Name: count, dtype: int64

In [11]:
df[
    [
        "nom_prenom",
        "date_recrutement",
        "anciennete",
    ]
].head(10)

           nom_prenom date_recrutement  anciennete
0       ABARAY Lahcen       2001-03-30          25
1       ADILA  Miloud       1995-11-13          30
2       ADMOR Mohamed       1992-10-12          33
3   AIT JEDDI Mohamed       1994-02-01          32
4   AL OUATIQ  Latifa       1995-08-01          31
5     AMAJOUD  Lahcen       1994-01-01          32
6   AMSAGGUINE Rachid       2001-11-01          24
7  BENMOHAMED  Lahcen       1995-06-01          31
8    DIBI  El Mostafa       1991-08-01          35
9  EL FELLAKI Khadija       1995-08-01          31

In [12]:
df[
    [
        "nom_prenom",
        "age",
        "anciennete",
        "annee_recrutement",
        "annee_retraite",
        "annees_avant_retraite",
    ]
].head(10)

,nom_prenom,age,anciennete,annee_recrutement,annee_retraite,annees_avant_retraite
0,ABARAY Lahcen,55,25,2001,2033.0,7.0
1,ADILA Miloud,63,30,1995,2026.0,0.0
2,ADMOR Mohamed,59,33,1992,2029.0,3.0
3,AIT JEDDI Mohamed,59,32,1994,2029.0,3.0
4,AL OUATIQ Latifa,59,31,1995,2030.0,4.0
5,AMAJOUD Lahcen,57,32,1994,2031.0,5.0
6,AMSAGGUINE Rachid,52,24,2001,2037.0,11.0
7,BENMOHAMED Lahcen,58,31,1995,2030.0,4.0
8,DIBI El Mostafa,62,35,1991,2026.0,0.0
9,EL FELLAKI Khadija,59,31,1995,2029.0,3.0